#!/usr/bin/env python3
"""
webapp.py — the owlet-bridge control panel (wyze-bridge style).

Everything configurable in the browser:
  - Owlet account credentials + region
  - Camera / TUTK settings (UID, AuthKey, AV account/password, start IOCTL, channel)
  - "Connect & Diagnose" runs the REAL Owlet login and streams every step to a
    live log pane — copy that log to share when login misbehaves.
  - Save settings -> persisted + the stream restarts against them.

Runs on :8088. go2rtc serves the actual video + its own UI on :1984.
"""

from __future__ import annotations

import json
import os
import threading
import time
from collections import deque

import requests
import yaml
from flask import Flask, Response, jsonify, render_template, request

app = Flask(__name__)

CONFIG_PATH = os.environ.get("CONFIG_PATH", "/config/owlet.yaml")
ENV_PATH = os.environ.get("ENV_PATH", "/config/owlet.env")
GO2RTC_API = os.environ.get("GO2RTC_API", "http://127.0.0.1:1984")

DEFAULTS = {
    "region": "world",
    "email": "",
    "password": "",
    "camera_name": "",
    "uid": "",
    "authkey": "",
    "av_account": "admin",
    "av_password": "",
    "iotype_start": "0x01FF",
    "av_channel": "0",
}

LOG: deque[str] = deque(maxlen=6000)
STATE: dict = {"candidates": [], "devices": None, "busy": False}


def log(msg: str = "") -> None:
    ts = time.strftime("%H:%M:%S")
    for line in str(msg).splitlines() or [""]:
        LOG.append(f"{ts}  {line}")


# --------------------------------------------------------------------------- #
# config
# --------------------------------------------------------------------------- #
def load_config() -> dict:
    cfg = dict(DEFAULTS)
    if os.path.exists(CONFIG_PATH):
        try:
            cfg.update(yaml.safe_load(open(CONFIG_PATH)) or {})
        except Exception:  # noqa: BLE001
            pass
    return cfg


def save_config(cfg: dict) -> None:
    merged = dict(DEFAULTS)
    merged.update({k: v for k, v in cfg.items() if k in DEFAULTS})
    os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
    with open(CONFIG_PATH, "w") as fh:
        yaml.safe_dump(merged, fh, default_flow_style=False)
    # Mirror to an env file the go2rtc exec sources before launching tutk_client.
    with open(ENV_PATH, "w") as fh:
        fh.write("# generated by owlet-bridge web UI\n")
        for k, v in merged.items():
            fh.write(f"OWLET_{k.upper()}={v}\n")


@app.get("/api/config")
def get_config():
    cfg = load_config()
    cfg["password"] = "********" if cfg.get("password") else ""
    cfg["authkey"] = cfg.get("authkey", "")
    return jsonify(cfg)


@app.post("/api/config")
def post_config():
    incoming = request.json or {}
    cfg = load_config()
    for k in DEFAULTS:
        if k in incoming and not (k == "password" and incoming[k] == "********"):
            cfg[k] = incoming[k]
    save_config(cfg)
    log("settings saved.")
    return jsonify({"ok": True})


# --------------------------------------------------------------------------- #
# diagnose (the real login)
# --------------------------------------------------------------------------- #
def _diagnose_worker(cfg: dict):
    STATE["busy"] = True
    try:
        from owlet_api import OwletAPI, OwletError
        if not cfg.get("email") or not cfg.get("password"):
            log("!! enter your Owlet email + password first.")
            return
        api = OwletAPI(cfg["region"], cfg["email"], cfg["password"], log=log)
        try:
            res = api.diagnose()
            STATE["candidates"] = res["candidates"]
            STATE["devices"] = res["devices"]
        except OwletError as e:
            log(f"!! login failed: {e}")
        except Exception as e:  # noqa: BLE001
            log(f"!! unexpected error: {e}")
    finally:
        STATE["busy"] = False


@app.post("/api/diagnose")
def diagnose():
    if STATE["busy"]:
        return jsonify({"error": "already running"}), 409
    cfg = load_config()
    # allow creds passed straight from the form (before saving)
    incoming = request.json or {}
    for k in ("region", "email", "password"):
        if incoming.get(k) and incoming[k] != "********":
            cfg[k] = incoming[k]
    LOG.clear()
    log("=== Owlet login diagnostic ===")
    threading.Thread(target=_diagnose_worker, args=(cfg,), daemon=True).start()
    return jsonify({"ok": True})


@app.get("/api/logs")
def logs():
    def gen():
        last = 0
        while True:
            cur = list(LOG)
            for ln in cur[last:]:
                yield f"data: {ln}\n\n"
            last = len(cur)
            time.sleep(0.4)
    return Response(gen(), mimetype="text/event-stream")


@app.get("/api/findings")
def findings():
    return jsonify({"candidates": STATE["candidates"], "devices": STATE["devices"]})


# --------------------------------------------------------------------------- #
# stream status / control
# --------------------------------------------------------------------------- #
@app.get("/api/status")
def status():
    cfg = load_config()
    have_login = bool(cfg.get("email") and cfg.get("password"))
    have_uid = bool(cfg.get("uid"))
    stream_up = False
    try:
        r = requests.get(f"{GO2RTC_API}/api/streams", timeout=4)
        if r.ok:
            data = r.json()
            owl = data.get("owlet") or {}
            stream_up = bool(owl.get("producers"))
    except Exception:  # noqa: BLE001
        pass
    return jsonify({
        "have_login": have_login, "have_uid": have_uid,
        "stream_up": stream_up, "busy": STATE["busy"],
        "go2rtc_ui": "/go2rtc/", "rtsp_hint": "rtsp://<host>:8554/owlet",
    })


@app.post("/api/stream/restart")
def restart_stream():
    try:
        requests.post(f"{GO2RTC_API}/api/restart", timeout=4)
        log("requested go2rtc restart.")
    except Exception as e:  # noqa: BLE001
        log(f"restart error: {e}")
    return jsonify({"ok": True})


@app.get("/")
def index():
    return render_template("index.html")


if __name__ == "__main__":
    if not os.path.exists(CONFIG_PATH):
        save_config(dict(DEFAULTS))
    app.run(host="0.0.0.0", port=int(os.environ.get("UI_PORT", "8088")), threaded=True)
