#!/usr/bin/env python3
"""
webapp.py — the owlet-bridge control panel (wyze-bridge style).

Everything configurable in the browser:
  - Owlet account credentials + region
  - Camera / TUTK settings (UID, AuthKey, AV account/password, start IOCTL, channel)
  - "Connect & Diagnose" runs the REAL Owlet login and streams every step to a
    live log pane — copy that log to share when login misbehaves.
  - Save settings -> persisted + the stream restarts against them.

Runs on :8088. go2rtc serves the actual video + its own UI on :1984.
"""

from __future__ import annotations

import json
import os
import re
import socket
import threading
import time
from collections import deque

import requests
from flask import Flask, Response, jsonify, render_template, request

app = Flask(__name__)

# Quiet the per-request access log so go2rtc / TUTK output is visible in
# `docker logs` (the status/findings polling was drowning everything out).
import logging  # noqa: E402
logging.getLogger("werkzeug").setLevel(logging.WARNING)

CONFIG_PATH = os.environ.get("CONFIG_PATH", "/config/owlet.yaml")
ENV_PATH = os.environ.get("ENV_PATH", "/config/owlet.env")
GO2RTC_API = os.environ.get("GO2RTC_API", "http://127.0.0.1:1984")

DEFAULTS = {
    "region": "world",
    "email": "",
    "password": "",
    "camera_name": "",
    "camera_dsn": "",
    "uid": "",
    "authkey": "",
    "av_account": "admin",
    "av_password": "",
    "iotype_start": "0x01FF",
    "av_channel": "0",
}

LOG: deque[str] = deque(maxlen=6000)
STATE: dict = {"candidates": [], "devices": None, "busy": False}


def log(msg: str = "") -> None:
    ts = time.strftime("%H:%M:%S")
    for line in str(msg).splitlines() or [""]:
        LOG.append(f"{ts}  {line}")


# --------------------------------------------------------------------------- #
# config
# --------------------------------------------------------------------------- #
def load_config() -> dict:
    cfg = dict(DEFAULTS)
    if os.path.exists(CONFIG_PATH):
        raw = ""
        try:
            raw = open(CONFIG_PATH).read()
        except Exception:  # noqa: BLE001
            raw = ""
        data: dict = {}
        try:
            data = json.loads(raw) or {}
        except Exception:  # noqa: BLE001
            # tolerate an old "key: value" (yaml-ish) config from earlier builds
            for line in raw.splitlines():
                line = line.strip()
                if not line or line.startswith("#") or ":" not in line:
                    continue
                k, _, v = line.partition(":")
                data[k.strip()] = v.strip().strip("\"'")
        cfg.update({k: v for k, v in data.items() if k in DEFAULTS})
    return cfg


def save_config(cfg: dict) -> None:
    merged = dict(DEFAULTS)
    merged.update({k: v for k, v in cfg.items() if k in DEFAULTS})
    os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
    with open(CONFIG_PATH, "w") as fh:
        json.dump(merged, fh, indent=2)
    # Mirror to an env file the go2rtc exec sources before launching tutk_client.
    with open(ENV_PATH, "w") as fh:
        fh.write("# generated by owlet-bridge web UI\n")
        for k, v in merged.items():
            fh.write(f"OWLET_{k.upper()}={v}\n")


@app.get("/api/config")
def get_config():
    cfg = load_config()
    cfg["password"] = "********" if cfg.get("password") else ""
    cfg["authkey"] = cfg.get("authkey", "")
    return jsonify(cfg)


@app.post("/api/config")
def post_config():
    incoming = request.json or {}
    cfg = load_config()
    for k in DEFAULTS:
        if k not in incoming:
            continue
        val = incoming[k]
        if k == "password" and val == "********":
            continue
        # Never wipe a saved non-empty value with an empty form field — this is
        # how the KMS-fetched UID/AuthKey used to get clobbered.
        if (val is None or val == "") and (cfg.get(k) or "") != "":
            continue
        cfg[k] = val
    save_config(cfg)
    log("settings saved.")
    return jsonify({"ok": True})


# --------------------------------------------------------------------------- #
# diagnose (the real login)
# --------------------------------------------------------------------------- #
def _diagnose_worker(cfg: dict):
    STATE["busy"] = True
    try:
        from owlet_api import OwletAPI, OwletError
        if not cfg.get("email") or not cfg.get("password"):
            log("!! enter your Owlet email + password first.")
            return
        api = OwletAPI(cfg["region"], cfg["email"], cfg["password"], log=log)
        try:
            res = api.diagnose()
            STATE["candidates"] = res["candidates"]
            STATE["devices"] = res["devices"]
        except OwletError as e:
            log(f"!! login failed: {e}")
        except Exception as e:  # noqa: BLE001
            log(f"!! unexpected error: {e}")

        # Fetch the camera's Kalay credentials from the KMS (needs only login).
        dsn = (cfg.get("camera_dsn") or "").strip()
        if dsn:
            try:
                creds = api.camera_credentials(dsn)
                cfg["uid"] = creds["uid"]
                cfg["authkey"] = creds.get("authkey") or ""
                if creds.get("av_password"):
                    cfg["av_password"] = creds["av_password"]
                save_config(cfg)
                log("[kms] saved UID / AuthKey / AV password to settings. "
                    "Click 'Save & (re)start stream'.")
            except Exception as e:  # noqa: BLE001
                log(f"[kms] could not fetch camera key: {e}")
        else:
            log("[kms] set 'Camera DSN' (e.g. OCD…) to auto-fetch the camera key.")
    finally:
        STATE["busy"] = False


@app.post("/api/diagnose")
def diagnose():
    if STATE["busy"]:
        return jsonify({"error": "already running"}), 409
    cfg = load_config()
    # allow creds passed straight from the form (before saving)
    incoming = request.json or {}
    for k in ("region", "email", "password", "camera_dsn"):
        if incoming.get(k) and incoming[k] != "********":
            cfg[k] = incoming[k]
    # Persist login + DSN now so they survive even before the KMS fetch — the
    # stream can resolve the camera key from these alone.
    save_config(cfg)
    LOG.clear()
    log("=== Owlet login diagnostic ===")
    log("build: kms-autofetch")
    threading.Thread(target=_diagnose_worker, args=(cfg,), daemon=True).start()
    return jsonify({"ok": True})


@app.get("/api/logs")
def logs():
    def gen():
        last = 0
        while True:
            cur = list(LOG)
            for ln in cur[last:]:
                yield f"data: {ln}\n\n"
            last = len(cur)
            time.sleep(0.4)
    return Response(gen(), mimetype="text/event-stream")


# --------------------------------------------------------------------------- #
# LAN camera discovery (Kalay UDP 63616)
# --------------------------------------------------------------------------- #
DISCOVERY_PORT = 63616
# Candidate TUTK/Kalay LAN-search probes (exact bytes vary by SDK version, so
# we send several and listen for any responder on 63616).
DISCOVERY_PROBES = [
    bytes.fromhex("f1411388"),
    bytes.fromhex("f1300000"),
    b"\x00\x00\x00\x00",
    b"\x01\x00\x00\x00",
    b"TUTK_SEARCH",
]
# A Kalay UID is ASCII: often 20 chars, sometimes grouped with dashes.
UID_TOKEN = re.compile(rb"[A-Z0-9]{6,}-?[A-Z0-9]{4,}-?[A-Z0-9]{0,8}")


def _discover_worker(target: str):
    LOG.clear()
    log("=== LAN camera discovery (UDP 63616) ===")
    log("NOTE: this only works if the container is on the same L2 network as the")
    log("camera — run it with `--network host` for broadcast, or give the camera IP.")
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
    s.settimeout(0.5)

    dests = []
    if target:
        dests.append(target.strip())
        log(f"probing {target.strip()} directly …")
    dests.append("255.255.255.255")
    log("broadcasting to 255.255.255.255 …")

    for d in dests:
        for p in DISCOVERY_PROBES:
            try:
                s.sendto(p, (d, DISCOVERY_PORT))
            except OSError as e:
                log(f"  send to {d} failed: {e}")

    found: dict[str, list[str]] = {}
    end = time.time() + 8
    while time.time() < end:
        try:
            data, addr = s.recvfrom(2048)
        except socket.timeout:
            continue
        except OSError:
            break
        toks = [t.decode(errors="ignore") for t in UID_TOKEN.findall(data)
                if 12 <= len(t) <= 24]
        log(f"  ◀ response from {addr[0]}:{addr[1]} ({len(data)} bytes) "
            f"hex={data[:32].hex()}")
        if toks:
            log(f"     UID candidate(s): {toks}")
            found.setdefault(addr[0], [])
            for t in toks:
                if t not in found[addr[0]]:
                    found[addr[0]].append(t)
    s.close()

    cands = []
    for ip, uids in found.items():
        for u in uids:
            cands.append({"field": f"LAN {ip} <uid>", "value": u})
    if cands:
        STATE["candidates"] = cands + STATE.get("candidates", [])
        log(f"\n[done] {len(cands)} UID candidate(s) on the LAN. "
            "Click one under Findings to fill the UID field.")
    else:
        log("\n[done] No camera responded on UDP 63616.")
        log("  → Likely the container can't reach the camera's network (use")
        log("    `--network host`), or the Dream Duo uses a different LAN probe.")
        log("  → Next step is the one-time AuthKey capture (which also yields the UID).")


@app.post("/api/discover")
def discover():
    if STATE["busy"]:
        return jsonify({"error": "busy"}), 409
    target = (request.json or {}).get("ip", "") if request.is_json else ""

    def run():
        STATE["busy"] = True
        try:
            _discover_worker(target)
        finally:
            STATE["busy"] = False

    threading.Thread(target=run, daemon=True).start()
    return jsonify({"ok": True})


@app.get("/api/findings")
def findings():
    return jsonify({"candidates": STATE["candidates"], "devices": STATE["devices"]})


# --------------------------------------------------------------------------- #
# stream status / control
# --------------------------------------------------------------------------- #
@app.get("/api/status")
def status():
    cfg = load_config()
    have_login = bool(cfg.get("email") and cfg.get("password"))
    have_uid = bool(cfg.get("uid"))
    stream_up = False
    try:
        r = requests.get(f"{GO2RTC_API}/api/streams", timeout=4)
        if r.ok:
            data = r.json()
            owl = data.get("owlet") or {}
            stream_up = bool(owl.get("producers"))
    except Exception:  # noqa: BLE001
        pass
    return jsonify({
        "have_login": have_login, "have_uid": have_uid,
        "stream_up": stream_up, "busy": STATE["busy"],
        "go2rtc_ui": "/go2rtc/", "rtsp_hint": "rtsp://<host>:8554/owlet",
    })


@app.post("/api/stream/restart")
def restart_stream():
    try:
        requests.post(f"{GO2RTC_API}/api/restart", timeout=4)
        log("requested go2rtc restart.")
    except Exception as e:  # noqa: BLE001
        log(f"restart error: {e}")
    return jsonify({"ok": True})


@app.get("/")
def index():
    return render_template("index.html")


if __name__ == "__main__":
    if not os.path.exists(CONFIG_PATH):
        save_config(dict(DEFAULTS))
    app.run(host="0.0.0.0", port=int(os.environ.get("UI_PORT", "8088")), threaded=True)
